version: '0.0.9.{build}'
image: Visual Studio 2022
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
configuration:
  - Release
nuget:
  disable_publish_on_pr: true
before_build:
  - cmd: dotnet --version
build_script:
  - cmd: dotnet build ./Content/Cnsola.csproj -v quiet
  - cmd: dotnet pack -v quiet
artifacts:
  - path: '**/*.nupkg'
skip_commits:
  files:
    - '**/*.md'
deploy:
- provider: NuGet
  server: https://f.feedz.io/jaxelr/cnsola/nuget/index.json
  on:
    branch: master
  api_key:
    secure: JGY8cM2ylez85zRpc/zQHPrRZzAzQ5zbJgwVD3gtH0Yk1zKBi8pIomdENBbtXhJM
  skip_symbols: true
